### ISSUE TITLE
React 15.4.0 兼容

### ISSUE THREAD

**Issue by yesmeck** [react-component/editor-core#1]
15.4.0 已经没有 `react/lib/CSSProperty.js` 了。

**Comment by mrasoahaingo** [comment]
Hi, I got exactly the same issue

**Comment by RaoHai** [comment]
reinstall dependences will fix this problem

**Comment by mrasoahaingo** [comment]
@RaoHai, what is the package to be installed?

**Comment by RaoHai** [comment]
npm install rc-editor-core@0.5.9

**Comment by mrasoahaingo** [comment]
I still got the same error :(

"antd": "^2.3.1",
    "normalizr": "^2.2.1",
    "rc-editor-core": "0.5.9",
    "react": "^15.4.0",
    "react-dom": "*",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0"

**Comment by mrasoahaingo** [comment]
My bad, I remove all node_module and reinstall all. That fixes the issue. Thanks!
