### ISSUE TITLE
prop-types warning

### ISSUE THREAD

**Issue by afc163** [react-component/editor-core#6]
http://127.0.0.1:8003/examples/simple.html

<img width="843" alt="image" src="https://cloud.githubusercontent.com/assets/507615/26099712/2fc5aa5c-3a5e-11e7-9f64-9851ea3944af.png">

找不到原因。

**Comment by RaoHai** [comment]
```tsx
import * as React from 'react';
```

会导致读 React.Proptype ...

**Comment by afc163** [comment]
...
